spring.datasource.driverClassName=org.postgresql.Driver
#create-drop update  create  none verify
spring.jpa.hibernate.ddl-auto=create-drop

spring.datasource.url=${SCHOOL_APP_DB_URL:jdbc:postgresql://localhost/school_management}
spring.datasource.username=${SCHOOL_APP_DB_USERNAME:postgres}
spring.datasource.password=${SCHOOL_APP_DB_PASSWORD}

#spring.jpa.show-sql=true

application.jwtSecret=${SCHOOL_APP_JWT_SECRET}
#10 days = 864000000; 1 h = 3600000; 10 min = 600000
application.jwtExpirationMs=864000000
